version: '4'
services:
  mysql:
    image: mysql:8.0.45
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Root@12345
#      MYSQL_DATABASE: order-service
#      MYSQL_USER: root
#      MYSQL_PASSWORD: Root@12345
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql